// web/src/pages/AddressList.tsx
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { addressApi } from '@/api';
import type { Address } from '@/types';

export default function AddressList() {
  const navigate = useNavigate();
  const [addresses, setAddresses] = useState<Address[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAddresses();
  }, []);

  const fetchAddresses = async () => {
    setLoading(true);
    try {
      const res = await addressApi.getAddresses();
      setAddresses(res.data);
    } catch (error) {
      console.error('Failed to fetch addresses:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSetDefault = async (id: string) => {
    try {
      await addressApi.setDefault(id);
      await fetchAddresses();
    } catch (error) {
      console.error('Failed to set default:', error);
      alert('设置失败');
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('确定要删除该地址吗？')) return;
    try {
      await addressApi.deleteAddress(id);
      await fetchAddresses();
    } catch (error) {
      console.error('Failed to delete address:', error);
      alert('删除失败');
    }
  };

  if (loading) {
    return <div className="loading">加载中...</div>;
  }

  return (
    <div className="page">
      <div className="flex-between mb-12">
        <div className="text-sm text-secondary">共 {addresses.length} 个地址</div>
        <button className="btn btn-sm btn-primary" onClick={() => navigate('/address/new')}>
          新增地址
        </button>
      </div>

      {addresses.length === 0 ? (
        <div className="empty">暂无地址</div>
      ) : (
        addresses.map((addr) => (
          <div key={addr.id} className="card mb-8" style={{ position: 'relative' }}>
            {addr.isDefault && (
              <div
                style={{
                  position: 'absolute',
                  top: 12,
                  right: 12,
                  background: 'var(--color-primary)',
                  color: '#fff',
                  fontSize: 10,
                  padding: '2px 8px',
                  borderRadius: 4,
                }}
              >
                默认
              </div>
            )}

            <div className="flex-between mb-8" style={{ paddingRight: 40 }}>
              <div>
                <span className="text-sm" style={{ fontWeight: 600 }}>
                  {addr.name}
                </span>
                <span className="text-sm text-secondary" style={{ marginLeft: 8 }}>
                  {addr.phone}
                </span>
              </div>
            </div>

            <div className="text-sm text-secondary mb-8">
              {addr.province} {addr.city} {addr.district} {addr.detail}
            </div>

            <div className="flex-center" style={{ gap: 8, justifyContent: 'flex-end' }}>
              {!addr.isDefault && (
                <button className="btn btn-sm btn-secondary" onClick={() => handleSetDefault(addr.id)}>
                  设为默认
                </button>
              )}
              <button
                className="btn btn-sm btn-secondary"
                onClick={() => navigate(`/address/${addr.id}/edit`)}
              >
                编辑
              </button>
              <button className="btn btn-sm btn-danger" onClick={() => handleDelete(addr.id)}>
                删除
              </button>
            </div>
          </div>
        ))
      )}
    </div>
  );
}

// web/src/pages/AddressList.vue
<template>
  <div class="page">
    <section class="section">
      <div class="section-header">
        <div class="section-title">收货地址</div>
        <div class="section-more" @click="router.push('/address/new')">
          添加地址
        </div>
      </div>

      <div v-if="loading" class="loading">加载中...</div>
      <div v-else-if="addresses.length === 0" class="empty">暂无收货地址</div>
      <div v-else class="flex-column" style="gap: 12px">
        <div
          v-for="addr in addresses"
          :key="addr.id"
          class="card"
          :style="{ border: addr.isDefault ? '2px solid var(--color-primary)' : 'none' }"
        >
          <div class="flex-between" style="margin-bottom: 8px">
            <div class="text-sm" style="font-weight: 600">
              {{ addr.name }}
            </div>
            <div v-if="addr.isDefault" style="font-size: 12px; color: var(--color-primary); padding: 2px 6px; background: #E8F8F5; border-radius: 4px">
              默认
            </div>
          </div>
          <div class="text-sm text-secondary" style="margin-bottom: 4px">
            {{ addr.phone }}
          </div>
          <div class="text-sm text-secondary">
            {{ addr.province }}{{ addr.city }}{{ addr.district }}{{ addr.detail }}
          </div>
          <div class="flex-center" style="gap: 8px; margin-top: 8px">
            <button class="btn btn-sm btn-secondary" @click="router.push(`/address/${addr.id}/edit`)">
              编辑
            </button>
            <button class="btn btn-sm btn-danger" @click="handleDelete(addr.id)">
              删除
            </button>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { addressApi } from '@/api'
import type { Address } from '@/types'

const router = useRouter()
const addresses = ref<Address[]>([])
const loading = ref(true)

onMounted(() => {
  fetchAddresses()
})

const fetchAddresses = async () => {
  try {
    const res = await addressApi.getAddresses()
    addresses.value = res.data
  } catch (error) {
    console.error('Failed to fetch addresses:', error)
  } finally {
    loading.value = false
  }
}

const handleDelete = async (id: string) => {
  if (!confirm('确定删除该地址吗？')) return

  try {
    await addressApi.deleteAddress(id)
    addresses.value = addresses.value.filter((addr: any) => addr.id !== id)
  } catch (error) {
    console.error('Failed to delete address:', error)
    alert('删除失败')
  }
}
</script>
