// web/src/pages/Coupons.vue
<template>
  <div class="page">
    <section class="section">
      <div class="flex-center" style="gap: 8px; margin-bottom: 12px">
        <div
          v-for="tab in tabs"
          :key="tab.value"
          :class="['btn btn-sm', activeTab === tab.value ? 'btn-primary' : 'btn-secondary']"
          @click="activeTab = tab.value"
          style="white-space: nowrap"
        >
          {{ tab.label }}
        </div>
      </div>

      <div v-if="loading" class="loading">加载中...</div>
      <div v-else-if="filteredCoupons.length === 0" class="empty">
        {{ activeTab === 'available' ? '暂无可用优惠券' : activeTab === 'used' ? '暂无已使用优惠券' : '暂无已过期优惠券' }}
      </div>
      <div v-else class="flex-column" style="gap: 12px">
        <div
          v-for="coupon in filteredCoupons"
          :key="coupon.id"
          class="coupon-card"
        >
          <div class="flex-center" style="gap: 8">
            <div class="flex-center coupon-amount">
              <span style="font-size: 24px; font-weight: 700; color: #E74C3C">
                ¥{{ coupon.amount }}
              </span>
            </div>
            <div style="flex: 1">
              <div class="text-sm" style="font-weight: 600; margin-bottom: 4px">
                {{ coupon.title }}
              </div>
              <div class="text-xs text-secondary" style="margin-bottom: 4px">
                满¥{{ coupon.minAmount }}可用 · {{ coupon.category }}
              </div>
              <div class="text-xs text-hint">
                有效期至：{{ formatDate(coupon.validUntil) }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { couponApi } from '@/api'
import type { Coupon } from '@/types'

const coupons = ref<Coupon[]>([])
const loading = ref(true)
const activeTab = ref<'available' | 'used' | 'expired'>('available')

const tabs = [
  { label: '可使用', value: 'available' as const },
  { label: '已使用', value: 'used' as const },
  { label: '已过期', value: 'expired' as const }
]

onMounted(() => {
  fetchCoupons()
})

const fetchCoupons = async () => {
  try {
    const res = await couponApi.getCoupons()
    coupons.value = res.data
  } catch (error) {
    console.error('Failed to fetch coupons:', error)
  } finally {
    loading.value = false
  }
}

const filteredCoupons = computed(() => {
  return coupons.value.filter(coupon => coupon.status === activeTab.value)
})

const formatDate = (timestamp: number) => {
  return new Date(timestamp).toLocaleDateString()
}
</script>

<style scoped>
.coupon-card {
  background: linear-gradient(135deg, #FFF5F5, #FFF);
  border: 1px solid #FFE4E1;
  border-radius: 12px;
  padding: 16px;
  position: relative;
  overflow: hidden;
}

.coupon-amount {
  width: 80px;
  height: 80px;
  background: linear-gradient(135deg, #FFE5E5, #FFF0F0);
  border-radius: 50%;
  border: 2px dashed #FFD1D1;
}

.coupon-card::after {
  content: '';
  position: absolute;
  bottom: 12px;
  right: 12px;
  font-size: 48px;
  color: rgba(231, 76, 60, 0.1);
  font-weight: 700;
  pointer-events: none;
}
</style>

// web/src/pages/Coupons.tsx
import { useEffect, useState } from 'react';
import { couponApi } from '@/api';
import type { Coupon } from '@/types';

export default function Coupons() {
  const [selectedTab, setSelectedTab] = useState<'available' | 'used' | 'expired'>('available');
  const [coupons, setCoupons] = useState<Coupon[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchCoupons();
  }, [selectedTab]);

  const fetchCoupons = async () => {
    setLoading(true);
    try {
      const res = await couponApi.getCoupons({ status: selectedTab });
      setCoupons(res.data);
    } catch (error) {
      console.error('Failed to fetch coupons:', error);
    } finally {
      setLoading(false);
    }
  };

  const tabs = [
    { label: '可用', value: 'available', count: 0 },
    { label: '已使用', value: 'used', count: 0 },
    { label: '已过期', value: 'expired', count: 0 },
  ];

  return (
    <div className="page">
      <div className="flex-center" style={{ gap: 8, marginBottom: 12, padding: '0 4px' }}>
        {tabs.map((tab) => (
          <div
            key={tab.value}
            className={`btn btn-sm ${selectedTab === tab.value ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => setSelectedTab(tab.value as 'available' | 'used' | 'expired')}
            style={{
              whiteSpace: 'nowrap',
              background: selectedTab === tab.value ? 'var(--color-primary)' : '#f5f5f5',
              color: selectedTab === tab.value ? '#fff' : '#666',
              border: 'none',
            }}
          >
            {tab.label}
          </div>
        ))}
      </div>

      {loading ? (
        <div className="loading">加载中...</div>
      ) : coupons.length === 0 ? (
        <div className="empty">暂无优惠券</div>
      ) : (
        <div className="flex-column" style={{ gap: 12 }}>
          {coupons.map((coupon) => (
            <div
              key={coupon.id}
              className="card"
              style={{
                display: 'flex',
                background: coupon.status === 'available' ? 'linear-gradient(135deg, #FF6B6B, #FF8E53)' : '#f5f5f5',
                color: coupon.status === 'available' ? '#fff' : '#999',
                overflow: 'hidden',
                position: 'relative',
              }}
            >
              <div
                className="flex-center"
                style={{
                  flex: '0 0 auto',
                  minWidth: 100,
                  padding: '16px 12px',
                  borderRight: coupon.status === 'available' ? '2px dashed rgba(255,255,255,0.3)' : '2px dashed #ddd',
                }}
              >
                <div style={{ fontSize: 28, fontWeight: 700, marginBottom: 4, textAlign: 'center' }}>
                  ¥{coupon.amount.toFixed(2)}
                </div>
                <div style={{ fontSize: 12, opacity: 0.9, textAlign: 'center' }}>
                  满¥{coupon.minAmount}可用
                </div>
              </div>

              <div
                style={{
                  flex: 1,
                  padding: '16px 12px',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                }}
              >
                <div>
                  <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 4 }}>
                    {coupon.title}
                  </div>
                  <div style={{ fontSize: 12, opacity: 0.9 }}>
                    {coupon.description}
                  </div>
                  {coupon.category && (
                    <div
                      style={{
                        fontSize: 10,
                        background: 'rgba(255,255,255,0.2)',
                        display: 'inline-block',
                        padding: '2px 8px',
                        borderRadius: 10,
                        marginTop: 6,
                      }}
                    >
                      {coupon.category}
                    </div>
                  )}
                </div>
                <div style={{ fontSize: 11, opacity: 0.8 }}>
                  有效期至：{new Date(coupon.validUntil).toLocaleDateString()}
                </div>
              </div>

              {coupon.status !== 'available' && (
                <div
                  style={{
                    position: 'absolute',
                    top: '50%',
                    right: '20px',
                    transform: 'translateY(-50%) rotate(-15deg)',
                    fontSize: 32,
                    fontWeight: 700,
                    opacity: 0.3,
                    letterSpacing: 4,
                  }}
                >
                  {coupon.status === 'used' ? '已使用' : '已过期'}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
