// web/src/pages/Messages.vue
<template>
  <div class="page">
    <section class="section">
      <div class="section-header">
        <div class="section-title">消息中心</div>
      </div>

      <div v-if="loading" class="loading">加载中...</div>
      <div v-else-if="messages.length === 0" class="empty">暂无消息</div>
      <div v-else class="flex-column" style="gap: 12px">
        <div
          v-for="msg in messages"
          :key="msg.id"
          class="card"
          style="cursor: pointer"
          :style="{ opacity: msg.isRead ? 0.6 : 1 }"
          @click="markAsRead(msg.id)"
        >
          <div class="flex-between" style="margin-bottom: 8px">
            <div class="text-sm" style="font-weight: 600">
              {{ msg.title }}
            </div>
            <div class="text-xs text-hint">
              {{ formatTime(msg.createdAt) }}
            </div>
          </div>
          <div class="text-sm text-secondary">{{ msg.content }}</div>
          <div class="flex-center" style="gap: 8px; margin-top: 8px">
            <span
              style="font-size: 12px; padding: 2px 8px; border-radius: 4px; background: #f0f0f0"
            >
              {{ msg.type === 'system' ? '系统' : msg.type === 'order' ? '订单' : '活动' }}
            </span>
            <span
              v-if="!msg.isRead"
              style="width: 6px; height: 6px; border-radius: 50%; background: var(--color-danger)"
            ></span>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { messageApi } from '@/api'
import type { Message } from '@/types'

const messages = ref<Message[]>([])
const loading = ref(true)

onMounted(() => {
  fetchMessages()
})

const fetchMessages = async () => {
  try {
    const res = await messageApi.getMessages()
    messages.value = res.data
  } catch (error) {
    console.error('Failed to fetch messages:', error)
  } finally {
    loading.value = false
  }
}

const markAsRead = async (id: string) => {
  try {
    await messageApi.markAsRead(id)
    messages.value = messages.value.map(msg =>
      msg.id === id ? { ...msg, isRead: true } : msg
    )
  } catch (error) {
    console.error('Failed to mark as read:', error)
  }
}

const formatTime = (timestamp: number) => {
  const now = Date.now()
  const diff = now - timestamp
  const minutes = Math.floor(diff / 60000)
  const hours = Math.floor(diff / 3600000)
  const days = Math.floor(diff / 86400000)

  if (minutes < 1) return '刚刚'
  if (minutes < 60) return `${minutes}分钟前`
  if (hours < 24) return `${hours}小时前`
  if (days < 7) return `${days}天前`
  return new Date(timestamp).toLocaleDateString()
}
</script>

// web/src/pages/Messages.tsx
import { useEffect, useState } from 'react';
import { messageApi } from '@/api';
import type { Message } from '@/types';

export default function Messages() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedType, setSelectedType] = useState<'all' | 'system' | 'order' | 'activity'>('all');

  useEffect(() => {
    fetchMessages();
  }, [selectedType]);

  const fetchMessages = async () => {
    setLoading(true);
    try {
      const params = selectedType !== 'all' ? { type: selectedType } : undefined;
      const res = await messageApi.getMessages(params);
      setMessages(res.data);
    } catch (error) {
      console.error('Failed to fetch messages:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleMarkAsRead = async (id: string) => {
    try {
      await messageApi.markAsRead(id);
      setMessages((prev) => prev.map((m) => (m.id === id ? { ...m, isRead: true } : m)));
    } catch (error) {
      console.error('Failed to mark as read:', error);
    }
  };

  const handleDeleteRead = async () => {
    if (!confirm('确定要删除所有已读消息吗？')) return;
    try {
      await messageApi.deleteMessages([]);
      await fetchMessages();
    } catch (error) {
      console.error('Failed to delete messages:', error);
    }
  };

  const typeLabels = {
    all: '全部',
    system: '系统',
    order: '订单',
    activity: '活动',
  };

  const typeIcons = {
    all: '📋',
    system: '🔔',
    order: '📦',
    activity: '🎉',
  };

  return (
    <div className="page">
      <div className="flex-center" style={{ gap: 8, marginBottom: 12, overflowX: 'auto', padding: '0 4px' }}>
        {(Object.keys(typeLabels) as Array<keyof typeof typeLabels>).map((key) => (
          <div
            key={key}
            className={`btn btn-sm ${selectedType === key ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => setSelectedType(key)}
            style={{
              whiteSpace: 'nowrap',
              background: selectedType === key ? 'var(--color-primary)' : '#f5f5f5',
              color: selectedType === key ? '#fff' : '#666',
              border: 'none',
            }}
          >
            {typeIcons[key]} {typeLabels[key]}
          </div>
        ))}
      </div>

      {loading ? (
        <div className="loading">加载中...</div>
      ) : messages.length === 0 ? (
        <div className="empty">暂无消息</div>
      ) : (
        <>
          <div className="flex-between mb-12">
            <div className="text-sm text-secondary">共 {messages.length} 条消息</div>
            <div className="text-sm text-primary" style={{ cursor: 'pointer' }} onClick={handleDeleteRead}>
              删除已读
            </div>
          </div>
          {messages.map((msg) => (
            <div
              key={msg.id}
              className={`card mb-8 ${!msg.isRead ? 'unread' : ''}`}
              style={{
                opacity: !msg.isRead ? 1 : 0.6,
                borderLeft: !msg.isRead ? '4px solid var(--color-primary)' : 'none',
                cursor: 'pointer',
              }}
              onClick={() => !msg.isRead && handleMarkAsRead(msg.id)}
            >
              <div className="flex-between mb-8">
                <div className="text-sm" style={{ fontWeight: 600 }}>
                  {msg.type === 'system' && '🔔'}
                  {msg.type === 'order' && '📦'}
                  {msg.type === 'activity' && '🎉'}
                  {' '}{msg.title}
                  {!msg.isRead && <span style={{ color: 'var(--color-danger)', marginLeft: 4 }}>未读</span>}
                </div>
                <div className="text-xs text-hint">
                  {new Date(msg.createdAt).toLocaleDateString()}
                </div>
              </div>
              <div className="text-sm text-secondary">{msg.content}</div>
            </div>
          ))}
        </>
      )}
    </div>
  );
}
